Repository hmcts/rd-profile-sync, pull requests merged in 2020-09, with the labels that each got.

#337 Nightly build fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-337

#341 Nighlty build fix 1
  src/main/java/uk/gov/hmcts/reform/profilesync/domain/ProfileSyncAudit.java
  src/main/java/uk/gov/hmcts/reform/profilesync/domain/ProfileSyncAuditDetails.java
  src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-341

#347 Nighlty build fix 1
  src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-347

#355 feat:removing search api pact test
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/profilesync/IdamConsumerTest.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-355

#361 Bump ups: Profile Sync Bump ups(RDCC-1876)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-361

#369 Bump : Bump ups library versions(RDCC-1876)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-369

#371 Bump org.flywaydb.flyway from 6.5.6 to 6.5.7
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-371
