Repository hmcts/rd-profile-sync, pull requests merged in 2020-12, with the labels that each got.

#426 RDCC-2072: adding 'pui-caa' to search query
  src/main/java/uk/gov/hmcts/reform/profilesync/schedular/UserProfileSyncJobScheduler.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-426

#428 Add sync branch method call
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-428

#431 Nightly build issue fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-431

#432 DTSPO-266 Enable self service read only access
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-432

#435 Bump Up : RDCC-2017 Address Jar version upgrades
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-435
