Repository hmcts/rd-profile-sync, pull requests merged in 2020-10, with the labels that each got.

#381 Upgrade TF to 0.12.2 and Azure RM to 2.20.0 - Master
  infrastructure/.terraform-version
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/sprod.tfvars
  infrastructure/state.tf
  infrastructure/terraform.tf
  infrastructure/test_config.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-381

#382 TF Upgrade to 13.3 and Azure RM to 2.25+
  infrastructure/.terraform-version
  infrastructure/output.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-382

#376 Build(deps) : Bump up jar versions(RDCC-1906)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-376

#385 Bumpups : Bump up jar version including owasp(RDCC-1933)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-385

#402 feat:adding suppressions for the build failures
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-402
