Repository hmcts/rd-profile-sync, pull requests merged in 2021-06, with the labels that each got.

#517 RDCC-2838 - changed all Gradle 7 deprecrated entries
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-517

#521 RDCC-2900 Nightly jenkins script changes done to enable security scan
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-521

#523 fix: RDCC-2960 Fixed CVE-2021-22118 and security scan reported issue
  Jenkinsfile_nightly
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-523

#528 Remove unwanted variables
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-528

#530 clean up local variables
  src/integrationTest/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-530
