Repository hmcts/rd-profile-sync, pull requests merged in 2021-07, with the labels that each got.

#532 updated order of command in security.sh to fix security scan
  security.sh
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-532

#531 Add auto-update config for PR branches
  .github/workflows/autoupdate.yml
Labels: DO NOT MERGE, ns:rd, prd:rd, rel:rd-profile-sync-pr-531

#533 fix : Fix CVE-2021-33037(RDCC-3141)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-533

#534 fix : remove bintray reference(RDCC-3150)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-534
