Repository hmcts/rd-profile-sync, pull requests merged in 2021-12, with the labels that each got.

#554 fix: RDCC-3655: Removed Idam consumer test as it is not required
  src/contractTest/java/uk/gov/hmcts/reform/profilesync/IdamConsumerTest.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-554

#555 RDCC-3768: Disabled fortify scan until further notice
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-555

#556 fix: RDCC-3773 patch log4j to the latest version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-556

#558 RDCC-3799: upgrading log4j to '2.16.0'
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-558

#557 RDCC-3786: Collating Dependabot PRs
  .dependabot/config.yml
  .github/dependabot.yml
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-557

#573 Fix: Upgrading log4j to fix CVE-2021-45105
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-573
