Repository hmcts/rd-profile-sync, pull requests merged in 2021-03, with the labels that each got.

#478 Update app insights key secret name
  charts/rd-profile-sync/Chart.yaml
  charts/rd-profile-sync/values.preview.template.yaml
  charts/rd-profile-sync/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-478

#482 fix: RDCC-2581: Fixed CVEs CVE-2021-25122, CVE-2021-25329
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-482

#488 RDCC-1985: removing unwanted suppressions
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-488
