Repository hmcts/rd-profile-sync, pull requests merged in 2022-02, with the labels that each got.

#576 Upgrade Gradle 7.3.3
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-576

#580 Rdcc 3945 newfix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-580

#581 fixed sonar issues issues
  src/test/java/uk/gov/hmcts/reform/profilesync/config/ServiceTokenGeneratorConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/profilesync/domain/ProfileSyncAuditTest.java
  src/test/java/uk/gov/hmcts/reform/profilesync/repository/ProfileSyncAuditDetailsRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-581

#582 RDCC-4048: CVE Fixes
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-582

#583 fix: Bump base java helm chart to 3.7.1
  charts/rd-profile-sync/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-583
