Repository hmcts/rd-profile-sync, pull requests merged in 2022-06, with the labels that each got.

#622 config: RDCC-4821 Configured renovate
  renovate.json
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-622

#634 config: RDCC-4858 added git hub workflow to auto merge renovate PRs
  .github/workflows/combine-prs.yml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-634

#635 RDCC-4858:ProfileSync Automerge Renovate PR's
  .github/workflows/combine-prs.yml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-635

#641 RDCC-4849: Collating DependaBot PRs
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-641

#663 RDCC-4946 Delete dependabot yaml file
  .github/dependabot.yml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-663
