Repository hmcts/rd-profile-sync, pull requests merged in 2022-05, with the labels that each got.

#617 RDCC-4633: Upgrading `gson` to `2.9.0` (CVE-2022-25647 Fix)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-617

#618 RDCC-4690: Suppressing `CVE-2016-1000027`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-618

#619 RDCC-4699: Upgrading `tomcat.embed` to `9.0.63` (`CVE-2022-29885` Fix)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-619

#620 CVE fix: Bumped spring dependencies version to 5.3.20
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-620
