Repository hmcts/rd-profile-sync, pull requests merged in 2022-09, with the labels that each got.

#673 CVE Fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-673

#674 RDCC-5447: Suppress Snakeyaml CVEs
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-674

#675 Idam client Upgrade
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-675

#676 Disable ApacheHTTPClient
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-676

#677 Revert "Disable ApacheHTTPClient"
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-677

#678 Rdcc apache disable
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-678

#679 Nightly Fix: Updating security.sh
  security.sh
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-679
