Repository hmcts/rd-profile-sync, pull requests merged in 2022-08, with the labels that each got.

#670 Address CVE-2020-23171 for all refdata REPOs
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-670

#671 RDCC-5261: Upgrading `postgresql` to `42.4.1`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-671

#672 Refactor code to remove the hard coding
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-672
