Repository hmcts/rd-profile-sync, pull requests merged in 2023-03, with the labels that each got.

#701 RDCC-6464: Adding Suppression for `CVE-2023-24998`
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-701

#697 Feat:Profile Sync API Spring boot upgrade
  Dockerfile
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-697

#702 Upgrade lib
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-702

#705 Addresses CVE-2023-28708
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-705

#706 Nightly build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-706
