Repository hmcts/rd-profile-sync, pull requests merged in 2023-05, with the labels that each got.

#715 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-715

#717 DTSRD-456: fix CVE-2023-28709
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-717

#716 [RDCC-6746]upgrade deprecated methods to java 17
  src/integrationTest/java/uk/gov/hmcts/reform/profilesync/SpringBootIntTest.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-716
