Repository hmcts/rd-profile-sync, pull requests merged in 2023-06, with the labels that each got.

#720 DTSRD-550: fix CVE-2023-20883
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-720

#721 Update renovate
  renovate.json
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-721

#718 [RDCC-6762]Update profileSync job to sync data between IDAM and SRD
  charts/rd-profile-sync/Chart.yaml
  charts/rd-profile-sync/values.yaml
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/profilesync/AuthorizationEnabledIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/profilesync/RunProfileSyncJobIntTest.java
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/reform/profilesync/client/CaseWorkerRefApiClient.java
  src/main/java/uk/gov/hmcts/reform/profilesync/domain/CaseWorkerProfile.java
  src/main/java/uk/gov/hmcts/reform/profilesync/schedular/UserProfileSyncJobScheduler.java
  src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/profilesync/domain/CaseWorkerProfileTest.java
  src/test/java/uk/gov/hmcts/reform/profilesync/helper/MockDataProvider.java
  src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-718

#722 Increase Mutation coverage for Profile Sync
  src/test/java/uk/gov/hmcts/reform/profilesync/domain/ProfileSyncAuditDetailsIdTest.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-722

#719 Update README.md
  README.md
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-719

#724 [RDCC-6762]Quick fix for the profile sync for caseworker users
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/profilesync/RunProfileSyncJobIntTest.java
  src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-724

#725 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-725

#726 Rdcc 6762 -fix cwd user failure
  src/integrationTest/java/uk/gov/hmcts/reform/profilesync/RunProfileSyncJobIntTest.java
  src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/profilesync/domain/CaseWorkerProfileTest.java
  src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-726

#727 DTSRD-175: remove suppression
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-727
