Repository hmcts/rd-profile-sync, pull requests merged in 2023-07, with the labels that each got.

#729 Update guava to 32.0.1
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-729

#730 [RDCC-6802]Profile Sync to verify if user exists in the SRD
  src/integrationTest/java/uk/gov/hmcts/reform/profilesync/AuthorizationEnabledIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/profilesync/RunProfileSyncJobIntTest.java
  src/main/java/uk/gov/hmcts/reform/profilesync/client/CaseWorkerRefApiClient.java
  src/main/java/uk/gov/hmcts/reform/profilesync/domain/response/GetCaseWorkerProfileResponse.java
  src/main/java/uk/gov/hmcts/reform/profilesync/service/CaseWorkerAcquisitionService.java
  src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/CaseWorkerAcquisitionServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/profilesync/domain/response/GetCaseWorkerProfileResponseTest.java
  src/test/java/uk/gov/hmcts/reform/profilesync/helper/MockDataProvider.java
  src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/CaseWorkerAcquisitionServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileUpdateServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-730

#731 testing app insights
  lib/applicationinsights.json
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-731

#732 App insights fix
  lib/applicationinsights.json
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-732

#734 Increase in Page size to fix prod sync issue
  src/integrationTest/resources/application.yaml
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-734

#735 [RDCC-6898]Populate option to see Profile sync log in Azure Portal
  src/integrationTest/resources/application.yaml
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-735

#736 CVE suppression CVE-2023-34034
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-736
