Repository hmcts/rd-profile-sync, pull requests merged in 2023-11, with the labels that each got.

#747 DTSRD-1629.Provisioning perftest server for profile-sync
  audit.json
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-profile-sync-pr-747

#749 Dtsrd 1629- running perftest
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-profile-sync-pr-749

#750 Update application.yaml to add schema to connection string
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-750

#751 Dtsrd 1629.provisioning v15 servers
  infrastructure/main.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-profile-sync-pr-751

#753 Update application.yaml. fixing connection string
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-753

#761 Update application.yaml. revertign changes to connection string
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-761

#763 DTSRD-1466.Updating schema parameter with hibernate
  audit.json
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/profilesync/repository/ProfileSyncAuditDetailsRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/profilesync/repository/ProfileSyncAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/profilesync/repository/ProfileSyncConfigRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/profilesync/repository/SyncConfigRepositoryTest.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-763

#764 DTSRD-1173-1.adding Zaproxy fix
  audit.json
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-764

#765 Update acb.tpl.yaml
  acb.tpl.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-765

#772 DTSRD-1793.migrating perftest from V11 to V15
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-profile-sync-pr-772
