Repository hmcts/rd-profile-sync, pull requests merged in 2024-06, with the labels that each got.

#867 DTSRD-2802
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-867

#873 fix PiTest issues
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-873

#875 Fix flyway schema issues on ithc
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-875

#876 DTSRD-2895
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-profile-sync-pr-876

#877 DTSRD-2845: Resize PG flexible server instance
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-profile-sync-pr-877
