Repository hmcts/rd-profile-sync, pull requests merged in 2024-05, with the labels that each got.

#818 Update schema ownership
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-818, aat/destroy, prod/destroy

#835 force user permissions
  infrastructure/main.tf
Labels: ns:rd, prd:rd, aat/destroy, prod/destroy, rel:rd-profile-sync-pr-835

#836 Remove logging
  src/main/java/uk/gov/hmcts/reform/profilesync/service/impl/ProfileSyncServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-836

#837 Update build.gradle. Fix Pit test
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-837

#838 Disable spot instances
  charts/rd-profile-sync/Chart.yaml
  charts/rd-profile-sync/values.yaml
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-838

#839 Delete single server from demo
  Jenkinsfile_CNP
  infrastructure/main.tf
Labels: ns:rd, prd:rd, aat/destroy, rel:rd-profile-sync-pr-839, demo/destroy

#854 DTSRD-2750.Delete single server
  Jenkinsfile_CNP
  charts/rd-profile-sync/Chart.yaml
  charts/rd-profile-sync/values.aat.template.yaml
  charts/rd-profile-sync/values.yaml
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/destroy, prod/destroy, rel:rd-profile-sync-pr-854

#855 Update Jenkinsfile_CNP - syncing demo with master
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-855

#856 Dtsrd 2766
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/uk/gov/hmcts/reform/profilesync/ProfileSyncApplication.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-856

#863 Version upgrade azurerm
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-profile-sync-pr-863
