Repository hmcts/rd-profile-sync, pull requests merged in 2024-07, with the labels that each got.

#878 Removed deprecated library
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-878

#879 DTSRD-3041
  src/main/resources/testcontainers.properties
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-879

#881 Update .terraform-version
  infrastructure/.terraform-version
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/prod.tfvars
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-profile-sync-pr-881

#880 Dtsrd 3041
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  src/main/resources/testcontainers.properties
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-880

#742 DTSRD-85: Update Profile Sync to Spring Boot 3
  build.gradle
  config/owasp/suppressions.xml
  gradle.properties
  src/main/java/uk/gov/hmcts/reform/profilesync/ProfileSyncApplication.java
  src/main/java/uk/gov/hmcts/reform/profilesync/client/UserProfileClient.java
  src/main/java/uk/gov/hmcts/reform/profilesync/domain/ProfileSyncAudit.java
  src/main/java/uk/gov/hmcts/reform/profilesync/domain/ProfileSyncAuditDetails.java
  src/main/java/uk/gov/hmcts/reform/profilesync/domain/ProfileSyncAuditDetailsId.java
  src/main/java/uk/gov/hmcts/reform/profilesync/domain/SyncJobConfig.java
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-742, aat/add-or-update, prod/add-or-update

#898 Fix build
  audit.json
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-898

#911 Update build.gradle. Fix Build
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-911

#914 Update build.gradle. Fix Build
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-profile-sync-pr-914
